sdbus++: Append 'common' namespace to enums
When an enum is used as a method arg, the generated aserver.hpp wasn't
compiling because the "xyz::openbmc_project::" namespace wasn't found as
a type in these two places:

```
Control/Failover/aserver.hpp:78:133: error: template argument 1 is invalid [-Wtemplate-body]
78 | using value_types = std::tuple<xyz::openbmc_project::control::Failover::Requester, std::map<std::string, std::variant<bool>>>;
```

and
```
Control/Failover/aserver.hpp:97:49: error: parse error in template argument list [-Wtemplate-body]
97 | utility::tuple_to_array(message::types::type_id<xyz::openbmc_project::control::Failover::Requester, std::map<std::string, std::variant<bool>>>());
```

Fix this by updating property.py to append the sdbusplus::common
namespace to enums to make them fully qualified, i.e:

```
using value_types = std::tuple<sdbusplus::common::xyz::openbmc_project::control::Failover::Requester, std::map<std::string, std::variant<bool>>>;
```

This applies to enums used everywhere. I didn't see a way to only make
the change for the 2 spots listed above.

Tested:
* The aserver.hpp properly compiles now.
* A full image still builds.

Change-Id: I0083b1d442e1aed0242b4c5522b3fe93aa67f06b
Signed-off-by: Matt Spinler <spinler@us.ibm.com>